# -*- coding: utf-8 -*-
"""BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7btLl7Je5gbkXzrx-vAt8MaVzmLAg3M

#Importing TensorFlow Libraries for Text Processing
"""

import tensorflow_hub as hub
import tensorflow_text as text

"""#URLs for TensorFlow BERT Models"""

preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

"""#Creating a Keras Layer with BERT Preprocessing Model"""

bert_preprocess_model = hub.KerasLayer(preprocess_url)

"""#Preprocessing Text Using BERT Model"""

text_test = ['Malla Reddy founded the college Malla Reddy', 'nice College indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

"""#Retrieving the Input Mask from Preprocessed Text"""

text_preprocessed['input_mask']

"""#Retrieving Input Type IDs from Preprocessed Text"""

text_preprocessed['input_type_ids']

"""#Retrieving Input Word IDs from Preprocessed Text"""

text_preprocessed['input_word_ids']

"""#Creating a Keras Layer with BERT Encoder Model"""

bert_model = hub.KerasLayer(encoder_url)

"""#Encoding Preprocessed Text Using BERT Model"""

bert_results = bert_model(text_preprocessed)

"""#Retrieving Keys from BERT Model Results"""

bert_results.keys()

"""#Retrieving Pooled Output from BERT Model Results"""

bert_results['pooled_output']

"""#Retrieving Encoder Outputs from BERT Model Results"""

bert_results['encoder_outputs']

